version: '3.8'

volumes:
  pg-data:

services:
  social-app:
    restart: always
    build: ./
    command: ./wait-for-postgres.sh db ./social-app
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=lhj9BfPUGYzhyTAZYltEj37ZKQeOVu6C