port: ":8000"
log_level: "debug"

db:
  username: "nermiabh"
  host: "dpg-cg6o0vg2qv28u2q3eplg-a"
  port: "5432"
  dbname: "socialldb"
  password: "lhj9BfPUGYzhyTAZYltEj37ZKQeOVu6C"
  sslmode: "disable"