port: ":8000"
log_level: "debug"

db:
  username: "nermiabh"
  host: "dpg-cghcmdd269v15el5igq0-a"
  port: "5432"
  dbname: "socialldb_4aod"
  password: "dfIQaZaymZWRBxI8aoTms1lP5KDkejz4"
  sslmode: "disable"